### PR TITLE
fix: update error message schema to match connexion ProblemException

### PR DESCRIPTION
**Pull request by danieljhegeman**
- #3067 

### Reviewers
**Functional:** 
@Bento007 
**Readability:** 

---

## Changes
- add
- remove
- modify

### CODE REVIEW

**Review by Bento007 — COMMENTED** [review]
Did you also fix this in the error responses from app?

**Comment by Bento007** [comment]
https://github.com/chanzuckerberg/single-cell-data-portal/blob/cb8ac1765fcd71c1a99aca6521980170bb3fc594/backend/corpora/api_server/app.py#L166

**Comment by danieljhegeman** [comment]
Need to change the backend code to match the name, title, detail format in all scenarios where an array of errors can be returned.

**Comment by Bento007** [comment]
Follow the format specified here https://www.rfc-editor.org/rfc/rfc7807
```
   {
   "type": "https://example.net/validation-error",
   "title": "Your request parameters didn't validate.",
   "invalid-params": [ {
                         "name": "age",
                         "reason": "must be a positive integer"
                       },
                       {
                         "name": "color",
                         "reason": "must be 'green', 'red' or 'blue'"}
                     ]
   }
```

**Pull request closed without merging**
