### PR TITLE
feat(mirroring): Add support for mirroring dev to rdev

### PR DESCRIPTION
**Pull request by Bento007**
## Reason for Change

- When testing RDEV environment it's helps to mirror the database from dev to rdev for testing. Prior to this PR there was no simple way of doing this. These changes speed up testing and get us closer to rdev environments mirroring dev.
- #5274 

## Changes

- Modify database mirroring script to be compatible with rdev environements,
- Updat backend/Make to use rdev formatted database and user name when DEPLOYMENT_STAGE=rdev is present. 
- Add checks for compatible mirroring configuration.

## Testing steps

- Ran mirroring in an rdev environment and verified collections were present using the frontend.
`./backend/scripts/mirror_rds_data.sh dev rdev {rdev-name}`

### CODE REVIEW

**Review by atarashansky — COMMENTED** [review]
tysm for this pr, i needed this BAD

**Review by atarashansky — CHANGES_REQUESTED** [review]
Can we extend this to be able to mirror staging to rdev as well?

**Comment by Bento007** [comment]
Related to  #5437

**Comment by danieljhegeman** [comment]
obviated by #5662

**Pull request closed without merging**
