### PR TITLE
docs(test): 3192 Add E2E tests best practices

### PR DESCRIPTION
**Pull request by tihuan**
- #3192

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/3192

Added some best practices that I believe would be helpful for the team. Please provide feedback where you see 🙏 Thanks so much!

Preview link:

https://github.com/chanzuckerberg/single-cell-data-portal/tree/thuang-3192-add-testing-best-practices/frontend/tests#best-practices

### Reviewers
**Functional:** 
@nayib-jose-gloria 

**Readability:** 
@ashin-czi 
---

## Changes
- add
- remove
- modify

### CODE REVIEW

**Review by seve — CHANGES_REQUESTED** [review]
Need to read the README, but if you haven't already, double-check the licensing on the Datadog PDF

**Comment by tihuan** [comment]
@seve ooh good call! Let me check the pdf. Thank you!

**Comment by tihuan** [comment]
Yeah good idea! Will do 👍 Thanks!

**Comment by tihuan** [comment]
DO NOT MERGE until the slack thread is resolved!

https://chanzuckerbergteam.slack.com/archives/CHUCU58JJ/p1668537888679109

**Comment by tihuan** [comment]
@seve confirmed that Datadog does have a clause to prevent redistribution of their materials 👍 Will replace the PDF with their form link instead. Thank you!

**Comment by tihuan** [comment]
Removed the pdf 👍 Thanks again for flagging that, @seve !

**Comment by tihuan** [comment]
@seve PTAL thanks so much!

**Comment by ashin-czi** [comment]
LGTM!! Thanks for writing this up! :]

**Review by ashin-czi — APPROVED** [review]

**Pull request merged**
