### PR TITLE
feat(wmg): Remove the "Tissue" and "Gene" labels

### PR DESCRIPTION
**Pull request by ashin-czi**
## Reason for Change

- #4208
- If the reason for this PR's code changes are not clear in the issue, state value/impact

## Changes

- add
- remove
    - Removing label text above add tissue/gene buttons
- modify

## Testing steps

- Either list QA steps or reasoning you feel QA is unnecessary
- Describe how you made sure to know that your changes worked. Should allow someone else to go verify your code without in depth knowledge.
- "Unit tested only", "tested in rdev by a, b, c, verifying feature worked by... ", "manually ran pipeline locally with these results: ..."

### CODE REVIEW

**Comment by tihuan** [comment]
@ashin-czi sorry can you add a screenshot please 🙏 Just wanted to double check how the buttons line up with the Source Data one 😄 Thank you!

**Comment by ashin-czi** [comment]
> @ashin-czi sorry can you add a screenshot please 🙏 Just wanted to double check how the buttons line up with the Source Data one 😄 Thank you!

good call! This is how it looks currently:
image

**Comment by tihuan** [comment]
Thanks so much, @ashin-czi ! @hthomas-czi does that look good to you? Thanks!

**Comment by ashin-czi** [comment]
waiting on Harley approval

**Comment by hthomas-czi** [comment]
@tihuan @ashin-czi Looks great!

**Comment by tihuan** [comment]
Thanks so much @hthomas-czi ! Mergingg

**Pull request merged**
