### PR TITLE
docs: punctuation fix

### PR DESCRIPTION
**Pull request by federicomarini**
Simple punctuation fix ;)

### CODE REVIEW

**Review by seve — APPROVED** [review]

**Comment by tihuan** [comment]
Thanks so much for helping us improve the docs, @federicomarini 🙏♥️ I'm looking into the PR check failures now, which are unrelated to your change. Hopefully we'll resolve it soon and get your PR merged!

**Comment by federicomarini** [comment]
That's just a full stop in here, but yep, happy to help in improving the docs!

**Review by atolopko-czi — APPROVED** [review]
Thanks for the correction!

**Comment by atolopko-czi** [comment]
Not sure why GHA jobs are failing, but since this is a trivial change, I just replicated it on the base branch of this PR. Closing this PR.

**Pull request closed without merging**
