### PR TITLE
feat: create .nvmrc

### PR DESCRIPTION
**Pull request by seve**
### Reviewers
**Functional:** @tihuan 

**Readability:** @danieljhegeman 

---

## Changes
- add
   - `.nvmrc` to set a standard version of node for nvm to use
- modify
   - bump next.js to bump node-sass to allow node v16 

## Notes:
Node v16 was needed for m1 support

### CODE REVIEW

**Review by tihuan — COMMENTED** [review]
awesome thanks for adding and fixing this! LGTM 🤩 👏

**Review by tihuan — APPROVED** [review]

**Comment by seve** [comment]
@tihuan I might have missed something, but I don't think this minor bump allows us to close any issues, correct? Is the DoD for #1705 to update next to latest, or did we just want to get rid of the vuln?

**Comment by tihuan** [comment]
DoD of https://github.com/chanzuckerberg/single-cell-data-portal/issues/1705 is just upgrading the patch version and upgrade `node-sass` to the latest, which should get rid of the vuln!

So this PR should close #1705 🙆‍♂️ 

Thanks, @seve !

**Comment by seve** [comment]
Looks like this patch didn't solve our needs, [ongoing thread over here](https://github.com/vercel/next.js/pull/28710#issuecomment-1021665525)

**Pull request closed without merging**
