### PR TITLE
feat: add custom header X-Curation-Authorization for Discover API rdev auth

### PR DESCRIPTION
**Pull request by danieljhegeman**
Use this custom header to pass a Discover API access token when the Authorization header is already being used/ready by another auth layer

## Reason for Change

- #TICKET_NUMBER
- If the reason for this PR's code changes are not clear in the issue, state value/impact

## Changes

- add
- remove
- modify

## Testing steps

- Either list QA steps or reasoning you feel QA is unnecessary
- Describe how you made sure to know that your changes worked. Should allow someone else to go verify your code without in depth knowledge.
- "Unit tested only", "tested in rdev by a, b, c, verifying feature worked by... ", "manually ran pipeline locally with these results: ..."

## Checklist 🛎️

- [ ] Add product, design, and eng as reviewers for rdev review
- [ ] For UI changes, add screenshots/videos, so the reviewers know what you expect them to see
- [ ] For UI changes, add e2e tests to prevent regressions

### CODE REVIEW

**Comment by Bento007** [comment]
I'm pretty sure this shouldn't be needed https://github.com/chanzuckerberg/single-cell-infra/commit/9d7b97a8b6046a459c0d66513e4cfbb5112fc90b

**Comment by Bento007** [comment]
at least it would work if we could update auth0 in TFE

**Comment by danieljhegeman** [comment]
> I'm pretty sure this shouldn't be needed [chanzuckerberg/single-cell-infra@9d7b97a](https://github.com/chanzuckerberg/single-cell-infra/commit/9d7b97a8b6046a459c0d66513e4cfbb5112fc90b)

Not sure what you mean. What's your proposed change to the auth paradigm?

**Comment by danieljhegeman** [comment]
Not required. Can make dual-use of Curation API token in Authorization header.

**Pull request closed without merging**
