### PR TITLE
fix: track active vs tombstoned datasets correctly for API response

### PR DESCRIPTION
**Pull request by danieljhegeman**
- #2978 

### Reviewers
**Functional:** 
@Bento007 
**Readability:** 

---

## Changes
- modify algorithm for determining which datasets should be returned. Previous logic had a mistake because it was mutating the list while iterating over it, allowing possibility for datasets to sneak through without being reshaped if tombstoned datasets exist within the collection. cc @brianraymor

### CODE REVIEW

**Review by Bento007 — CHANGES_REQUESTED** [review]
Add a test to verify this works as expected

**Comment by danieljhegeman** [comment]
> Add a test to verify this works as expected

To recreate the exact scenario that was occurring would be extremely tedious, because it was only occurring in certain scenarios with certain arrangements of datasets with tombstones interspersed. 

The difference is in accidentally _skipping_ items in a list before (because I `pop`'d items out of the list); now I'm just doing a normal `for / in` loop.

That is to say, it's not a new feature. It's basically fixing a typo-equivalent bug.

**Comment by Bento007** [comment]
If we had proper test coverage then this would have shown up in the unit tests. It's an edge case we didn't account for in our tests and should be covered to prevent regression. This will make future changes to that code area more stable.

**Comment by danieljhegeman** [comment]
> If we had proper test coverage then this would have shown up in the unit tests. It's an edge case we didn't account for in our tests and should be covered to prevent regression. This will make future changes to that code area more stable.

Ok I'll produce something.

But bear in mind that edge cases are infinite. Testing is never perfect. There are many edge cases equivalent in degree to this one that we're not testing right now, only because we never screwed up the code in a way to reveal them in the first place.

**Comment by danieljhegeman** [comment]
Given the nature of the problem, the extremely narrow picture we'd be testing for, and the fact that we need to unblock curators (the problem isn't silent; it is known immediately if it is occurring because of the API schema check), we should just merge this now and come back and decide on how to add a test for this later, which may require a reworking of the shared test db data.

**Review by Bento007 — APPROVED** [review]
Great job investigating and fixing.

**Pull request merged**
