### PR TITLE
data update 20220112

### PR DESCRIPTION
**Pull request by atolopko-czi**
### Reviewers
**Functional:** 
@tihuan 

**Readability:** 
@tihuan 

---

## Changes
update backend data to 20220112, reflecting latest cell_type ordering algo

## QA steps (optional)
This has NOT been tested AT ALL.

### CODE REVIEW

**Review by tihuan — APPROVED** [review]
Woohoo! GO ANDREW 🤩 🚀 !

**Comment by tihuan** [comment]
Ah I think the commit message and PR title need to follow conventional commit format!

Maybe something like: `data: update 20220112`?

**Comment by atolopko-czi** [comment]
> Ah I think the commit message and PR title need to follow conventional commit format!
> 
> Maybe something like: `data: update 20220112`?

Yeah, I cannot seem to train myself on this one! 😆

**Comment by tihuan** [comment]
On Science Design System team, we use [commitizen](https://github.com/commitizen/cz-cli) cli tool to assist writing commit message:



If needed, we can add it to Single Cell too?

**Comment by atolopko-czi** [comment]
> On Science Design System team, we use [commitizen](https://github.com/commitizen/cz-cli) cli tool to assist writing commit message

The lint error is from the PR _title_, right? So not sure commitizen would help with that. But I suppose, similarly, we could use PR creation script to create our PRs and enforce the naming convention. (I'd sooner remove the lint check!)

**Comment by tihuan** [comment]
IIRC if there's only one commit in the PR, Github uses the commit message as the PR title, so commitizen works for that case. But not so sure when there's multiple commits in a PR 🤔  I think on SDS, people might just be manually changing the PR title in that case

PR creation script sounds great too!

**Pull request merged**
