### PR TITLE
feat(wmg): 3487 SVG download

### PR DESCRIPTION
**Pull request by tihuan**
- #3487 

### Reviewers
**Functional:** 

**Readability:** 

---

## Changes
- add
- remove
- modify

## Notes for Reviewer
To see the y-axis and dots rendered as SVG, follow the steps below:
1. Select blood, add gene `TSPAN6` and `MALAT1` for contrast
2. Once the chart is rendered, click on the download button
3. Once done, two new tabs will open - one shows y-axis and the other show the dots

Like so:

demo

### CODE REVIEW

**Comment by ashin-czi** [comment]
Sharing status:

I'm able to now download an SVG of the y-axis and the heatmap, but styling is very rough at the moment. Also still need to add the legend somehow.
CELLxGENE_gene_expression (44)

**Comment by ashin-czi** [comment]
Current status:

Created a rough x-axis, still needs work on the code side. Y-Axis label needs work as well with alignment based on the length of the name
CELLxGENE_gene_expression - 2023-01-24T141008 221

**Comment by ashin-czi** [comment]
@signechambers1 Are we only going to allow SVG downloads? Or are we giving them the option for both SVG or PNG?

**Comment by signechambers1** [comment]
@ashin-czi we're giving them the option of PNG or SVG, let me know if you have questions.

**Comment by ashin-czi** [comment]
@hthomas-czi @karenliang0 @signechambers1 

What do you guys think of having the legend in the top left to make use of that white space that's normally there?
image

**Comment by ashin-czi** [comment]
liver
spleen
bone-marrow
lung
blood

**Comment by signechambers1** [comment]
i defer to @hthomas-czi and @karenliang0 , thanks andrew!

**Comment by ashin-czi** [comment]
@signechambers1 This can now be tested in rdev! 

https://rdev-svg-download-2-frontend.rdev.single-cell.czi.technology/gene-expression

Let me know if you see any issues!

**Comment by karenliang0** [comment]
Can't get into github right now but I think it's an interesting suggestion!
We are really text heavy on the left side though and so I think adding the
legend there may overwhelm the balance of the page.

**Comment by signechambers1** [comment]
The resolution does look really good! Great work! Tagging @pablo-gar for SME review. Rdev link here: https://rdev-svg-download-2-frontend.rdev.single-cell.czi.technology/gene-expression

**Comment by ashin-czi** [comment]
now using SVG color scale plasma instead of href
blood (61)

**Comment by tihuan** [comment]
Fantastic work, @ashin-czi ! LGTM 🚀 !!

**Review by atarashansky — APPROVED** [review]
lgtm! great work

**Pull request merged**
