### PR TITLE
feat: 4567- E2E tests for Gene Expression Right Side Bar and Top Nav

### PR DESCRIPTION
**Pull request by victorikeokoro6**
Description
E2E tests for Right side bar and top Nav of Gene Expression

Ticket
#4567

Overview
The test aims to ensure that the right side bar (RSB) loads properly with the legend, methodology, and source data. Additionally, when the scaled checkbox is checked, gene expression should scale from 0 to 1, and the darkest color should show up in the dot plot. The methodology section should include a link to the scExpression documentation. Clicking on the cellxgene logo should take the user back to the data portal, and the help and documentation should link out to the cellxgene documentation. The test should verify that all these features are working as intended and are providing accurate information to the user.

### CODE REVIEW

**Comment by tihuan** [comment]
Added @ashin-czi since I'll be out till 5/8! Thank you!

**Review by charles-testco — CHANGES_REQUESTED** [review]
@victorikeokoro6  pls get rid of the beforeEach per Timmy's previous feedback.
Charles test descriptions to be Mocha format for consistency: "Should ...."
Finally check for overlap and merge tests, I think some scenarios are very similar with what I did in landingPage.tests.ts

**Comment by charles-testco** [comment]
> I noticed a lot of refactors for wheresMyGene.test.ts
> 
> I tried running these tests locally but many of them are failing.
> 
> Some examples, but there are more errors for other tests:
> 
> image image image image image
> 
> Is there something that I need for these tests to pass locally for me?
> 
> [Also I noticed that retries are commented out](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/frontend/playwright.config.ts#L102), was the plan not to retry tests anymore? I believe we should keep retries but I'm unsure if this was a conversation had with Timmy at some point, or if this was accidental and was meant to only be for local.

@ashin-czi the retry thingy is definitely a left over from local testing. As for refactoring, we generally shouldn't touch those tests except when we refactor and use the utilities we someime have to make changes.
@victorikeokoro6 pls check this out

**Comment by victorikeokoro6** [comment]
ok I would  check it out @ashin-czi @charles-testco

**Comment by victorikeokoro6** [comment]
Hi @charles-testco I have implemented the fixes to my tests

**Comment by victorikeokoro6** [comment]
I also looked into the failing into the failing tests, I don't know who mad the last changes to  wheresMyGene.test.ts

**Review by charles-testco — APPROVED** [review]

**Comment by charles-testco** [comment]
> @charles-testco thanks for fixing the PR 🙏
> 
> Can you please help run WMG tests locally to ensure everything passes before approving the PR?
> 
> Thanks so much!

Thanks a will

**Pull request merged**
