### PR TITLE
chore(cellguide): ChatGPT Help Icon Tooltip Styles

### PR DESCRIPTION
**Pull request by ashin-czi**
## Reason for Change

- #5407 

## Changes

- add
- remove
- modify
    - ChatGPT tooltip theme and stylings 

## Testing steps

- Either list QA steps or reasoning you feel QA is unnecessary
- Describe how you made sure to know that your changes worked. Should allow someone else to go verify your code without in depth knowledge.
- "Unit tested only", "tested in rdev by a, b, c, verifying feature worked by... ", "manually ran pipeline locally with these results: ..."

### CODE REVIEW

**Comment by tihuan** [comment]
Ooh yes! I reached out to the Playwright community about this yesterday and haven't heard anything yet.

But a solution I have in my branch is to NOT import any .tax files in the test files, since Playwright's file parser somehow doesn't know how to handle SVG files at the moment

I'll separate the commit out in a PR and get it merged, so hopefully that will unblock you!

**Comment by tihuan** [comment]
Here's the PR!

**Review by atarashansky — APPROVED** [review]
LGTM

**Comment by tihuan** [comment]
@ashin-czi I merged the test fix PR 👍 !

**Pull request merged**
