### PR TITLE
feat: wmg query endpoint impl with filter dim datasets metadata

### PR DESCRIPTION
**Pull request by atolopko-czi**
Part 4 of 4 of [story](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1959).

Branched off of https://github.com/chanzuckerberg/single-cell-data-portal/pull/2045

### Reviewers
**Functional:** 
@MDunitz 

**Readability:** 
@tihuan 

---

## Changes
* wmg query endpoint response now includes dataset metadata in the `filter_dimensions` section
* API spec changes (relative to prev pr):
    * `response_option` (enum) -> `include_filter_dims` (bool_)
    * `query` endpoint response: `filter_dimensions.datasets.collection_url` -> `collection_id`

### CODE REVIEW

**Review by tihuan — APPROVED** [review]
LGTM! Look forward to using the endpoints next week 🚀 !!

**Review by tihuan — APPROVED** [review]
LGTM! Somehow there's FE code in this PR that's merged into `main` already 👌

**Comment by atolopko-czi** [comment]
> LGTM! Somehow there's FE code in this PR that's merged into `main` already 👌

Ah, the parent branch may not have been updated to latest main, although this branch was.  It should all work out fine, since I'm ultimately just going to merge the all-in-one PR #2068  instead of the original 4 sequential PRs

**Comment by atolopko-czi** [comment]
This PR subsumed by https://github.com/chanzuckerberg/single-cell-data-portal/pull/2068.

**Pull request closed without merging**
