### PR TITLE
refactor: allow backend to support multiple APIs

### PR DESCRIPTION
**Pull request by atolopko-czi**
### Reviewers
**Functional:** 
@danieljhegeman @Bento007 

**Readability:** 
@MDunitz 

---

## Changes

Refactoring changes are to support the implementation of multiple, _independent_ APIs that can run under the same Flask app, and exist within a single git repo (monorepo pattern).  Each API exists in its own subdirectory of `backend/api` and is added to the Flask app, using Connexion's `add_api` method, which creates a Flask Blueprint for each API. Each API has its own Swagger UI page, and a new landing page has been added to link to each of the Swagger UIs.

* rename `backend/corpora` dir to `backend/api/data_portal` (causing lots of
package updates throughout code base)

* add backend/api/wmg for new WMG API (stubbed)

* OpenSpec API yml config files now reside under their respective API
subdirectory. Removed `backend/config`, moving corpora-api.yml to
`backend/api/data_portal` and added `backend/api/wmg/wmg-api.yml` file.

* leave all pipeline processing-related code under `backend/api/data_portal`
for now, acknowleding that this code now needs to be moved outside of
`backend/api`

* move shared API-related files from `backend/corpora/api_server` up to
`backend/api`: app.py, requirements.txt, README.md, db.py

* replace custom swagger UI index page with connexion's swagger UI; each
API's swagger UI is now accessible under wmg/ui/ and dp/ui/

* add index landing page with links to respective swagger uis

### CODE REVIEW

**Review by Bento007 — CHANGES_REQUESTED** [review]
- Delete everything `cloudfront_invalidator`
- mv "backend/api/data_portal/lambdas/api" "backend/api/data_portal/api"
- mv "backend/api/data_portal/lambdas/upload_failure/upload.py" backend/api/data_portal/upoad_failures/upload.py
- Is there a reason to have the backend/api/data_portal/config directory. We can move database.ini one level up.

**Comment by atolopko-czi** [comment]
> * Delete everything `cloudfront_invalidator`
> * mv "backend/api/data_portal/lambdas/api" "backend/api/data_portal/api"
> * mv "backend/api/data_portal/lambdas/upload_failure/upload.py" "backend/api/data_portal/upoad_failures/upload.py"
> * Is there a reason to have the backend/api/data_portal/config directory. We can move database.ini one level up.

I was thinking I'd just limit the changes to what was needed to separate the APIs, leaving all the Data Portal API refactoring for another effort. But I'll take a stab at this, since we're already in deep on the number of file changes!

**Comment by Bento007** [comment]
at a minimum Delete cloudfront_invalidator. It has already been removed from main.

**Comment by atolopko-czi** [comment]
> at a minimum Delete cloudfront_invalidator. It has already been removed from main.

done!

**Comment by atolopko-czi** [comment]
closing until actively working on this again

**Pull request closed without merging**
