### PR TITLE
feat: wmg api primary filter dims endpoint

### PR DESCRIPTION
**Pull request by atolopko-czi**
For [story](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2051).

Branched off of PR #2068, so wait for that PR to be merged before CR'ing, for reduced diff.

### Reviewers
**Functional:** 
@MDunitz 

**Readability:** 
@tihuan 

---

## Changes
* impl `primary_filter_dimensions` endpoint: update openapi spec, api impl method, WmgQuery class
* cube test fixture logic now supports exclusion of specific coords (rows) to facilitate more detailed testing of inter-related dimensions (e.g. an organism dim value implies an independent set of gene dim values).
* renamed WmgQuery.query() to expression_summary() for differentation from new method for primary_filter_dimensions().

## Testing
* Unit tests
* Localhost Docker API call (dummy data cube):
```
❯ curl -X GET "http://backend.corporanet.local:5000/wmg/v1/primary_filter_dimensions" -H "accept: application/json"  | jq .

{
  "gene_terms": {
    "NCBITaxon:10001": [
      {
        "ENSG00000000003": "TSPAN6"
      },
      {
        "ENSG00000000005": "TNMD"
      },
      {
        "ENSG00000000419": "DPM1"
      }
    ],
    "NCBITaxon:10002": [
      {
        "ENSG00000000003": "TSPAN6"
      },
      {
        "ENSG00000000005": "TNMD"
      },
      {
        "ENSG00000000419": "DPM1"
      }
    ],
    "NCBITaxon:1000278": [
      {
        "ENSG00000000003": "TSPAN6"
      },
      {
        "ENSG00000000005": "TNMD"
      },
      {
        "ENSG00000000419": "DPM1"
      }
    ]
  },
  "organism_terms": [
    {
      "NCBITaxon:10001": "Sciurus"
    },
    {
      "NCBITaxon:10002": "Sciurus aberti aberti"
    },
    {
      "NCBITaxon:1000278": "Acheilognathus tabira tohokuensis"
    }
  ],
  "snapshot_id": "4e70b2b4a8b145c48c488951abd7bec5",
  "tissue_terms": [
    {
      "UBERON:0000000": "processual entity"
    },
    {
      "UBERON:0000002": "uterine cervix"
    },
    {
      "UBERON:0000003": "naris"
    }
  ]
}
```

### CODE REVIEW

**Review by tihuan — APPROVED** [review]
API LGTM! What's the estimated amount of items for each primary filter? Is it gonna be over 1K? If so I'll need to do something in the UI to make it render fast lol

Thank you!

**Comment by atolopko-czi** [comment]
> API LGTM! What's the estimated amount of items for each primary filter? Is it gonna be over 1K? If so I'll need to do something in the UI to make it render fast lol
> 
> Thank you!

I'm not sure yet, but it will be large, since there are ~100K genes, across all organisms.  I expect some iteration will be required to optimize this with caching, and maybe relying upon etags to ensure caches are invalidated properly.

**Comment by tihuan** [comment]
> > API LGTM! What's the estimated amount of items for each primary filter? Is it gonna be over 1K? If so I'll need to do something in the UI to make it render fast lol
> > 
> > Thank you!
> 
> I'm not sure yet what the total response size will be in bytes, but it will be large, since there are ~100K genes, across all organisms.  I expect some iteration will be required to optimize this with caching, and maybe relying upon etags to ensure caches are invalidated properly.  
> 
> There's only a handful of organisms, and O(100) tissues (?).  So genes are the performance problem.  Each organism (mouse, human) will have a disjoint set of those genes, fwiw.

Oh perfect! Genes selector already got rendering optimization thanks to Seve, so if other filters won't go over 1000 items, then FE won't do the same optimization on them yet until needed!

Yeah iterating on caching stuff later sounds good too 😊👍

Thank you!

**Comment by atolopko-czi** [comment]
will be merge as part of https://github.com/chanzuckerberg/single-cell-data-portal/pull/2115

**Pull request closed without merging**
