### PR TITLE
feat: refine navigation bar UI to match mocks (#1600)

### PR DESCRIPTION
**Pull request by frano-m**
### Reviewers
**Functional:** 
@tihuan 

---

## Changes
Updated navigation bar UI to match mocks: [navigation bar](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1564%3A18513), [navigation bar states](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2216%3A28615).

### CODE REVIEW

**Comment by tihuan** [comment]
@frano-m @MillenniumFalconMechanic for the failing smoke test, is it passing locally? Thank you!

**Comment by tihuan** [comment]
Looks really great! Thanks so much for the PR, @frano-m 🎉 !

Just a few tiny nits 👍 

1. I think we just need to flip the logic for show/hide My Collections link. Right now it's showing the link when logged out and not showing when logged in!
2. I think we need to hide the down caret for the Log In button, since there's no dropdown
Screen Shot 2021-11-09 at 9 57 22 AM

1. When logged in My Collections link is not available 
Screen Shot 2021-11-09 at 9 56 57 AM

1.  When a user only provides email and not their first name, the name initial circle's contrast is not eligible. Maybe @hthomas-czi could help here on what the initial text color and/or what the background color should be? Thank you!
Screen Shot 2021-11-09 at 9 56 40 AM

**Comment by hthomas-czi** [comment]
Looks great! 

Per Timmy's comment for users who only provide their email and not their first name, could we get rid of the circle all together and just show "Account" with the appropriate style?

**Comment by frano-m** [comment]
Hi @tihuan,

I have fixed the “my collections” logic, and have updated the email-only display as per Haley’s comments.
After confirming with Harley, I have kept the caret to the right of the “log in” link as per the mocks.

Thanks again,

Fran.

**Review by tihuan — APPROVED** [review]
Awesomeee! This looks super neat ✨ 🤩 Thanks so much for updating this, @frano-m !! 🙏 🚀

**Pull request merged**
