### PR TITLE
fix: set refetch to false for collection detail. #2204

### PR DESCRIPTION
**Pull request by MillenniumFalconMechanic**
### Reviewers
**Functional:** 
@seve 

---

## Changes
- Added `refetchOnWindowFocus: false` for collection detail-related React Query fetches. The general approach for handling of stale data on the FE is currently being reviewed (see [Determine approach for updating search results when backend data changes](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1809) and [Add Cloudfront caching+invalidation for datasets/index and collections/index endpoints](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1899).

### CODE REVIEW

**Comment by seve** [comment]
I think a better solution for [this bug](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2204) would be to introduce a pending state that is overlaid on state received from the backend

**Review by seve — COMMENTED** [review]
Not sure if this is the right fix for the problem

**Comment by MillenniumFalconMechanic** [comment]
Hey @seve, thank you for your quick review. I have been discussing this PR with @NoopDog  and wanted to give you some background on what we’re thinking.

#### Current State
1. It looks like the application does not currently support the detection of concurrent modifications of the same record by users. It seems to be “the last update wins”.

1. The different sections of the form behave differently with respect to concurrent modification detection:

    The top portion of the form (e.g. name, description, contact) is not currently updated from or merged with refetched data when the user clicks away and back again.

    The bottom part of the form (e.g. links) is always reset to the refetched data when the user clicks away and back again. (This is the defect Jason reported that we’re trying to fix here.)


#### Going Forward
We think a longer-term “best” solution here is something along the lines:

1. Implement optimistic locking on the record on the BE.
1. Detect and reject the (rare) concurrent modifications with appropriate user messaging.
1. Avoid the detection/merging of these cases in the FE.

For now, we would like to go ahead and suppress the refetch as per the PR. This fixes the UI defect, adds consistent form functionality and is consistent with the current concurrent modification behavior (that is, it maintains “last update wins”). 

We feel merging or marking changed links adds complexity, requires input from product/UX and isn't in line with the longer-term "best" solution I am proposing above.

I feel it might be fastest to discuss this on a call (with @brianraymor) given this requires input from product and possibly a longer-term solution.

**Comment by seve** [comment]
> For now, we would like to go ahead and suppress the refetch as per the PR. This fixes the UI defect, adds consistent form functionality and is consistent with the current concurrent modification behavior (that is, it maintains “last update wins”).

Taking a look at some context around the changes, it looks like the breaking change was the introduction of the `useEffect` hook on any changes to `data`.  If this change is only present until `isFilterEnabled` is removed, then I'm happy to green light this.

Maybe add a comment similar to https://github.com/chanzuckerberg/single-cell-data-portal/blob/635ebd0be4d5c3fb197b8c887f149cf396bb3a6a/frontend/src/components/CreateCollectionModal/components/Content/index.tsx#L141

**Pull request merged**
