### PR TITLE
fix: filter out errant duplicate assets on Discover API responses

### PR DESCRIPTION
**Pull request by danieljhegeman**
## Reason for Change

- #5136

## Testing steps

- tested against dev with adhoc deploy ✅

### CODE REVIEW

**Review by Bento007 — CHANGES_REQUESTED** [review]
Where is the test for this?

**Comment by danieljhegeman** [comment]
@Bento007 https://czi-sci.slack.com/archives/C02UGUV5R3J/p1688679605578739?thread_ts=1688595007.007299&cid=C02UGUV5R3J

**Comment by Bento007** [comment]
Given the above thread, I recommend pulling out the filter into it's own function that takes in the list of assets and filters them. This will allow us to not only test it works, but also removing the code will be easier.

**Comment by maniarathi** [comment]
+1 to what @Bento007 said. This PR needs tests. Data integrity issues are not ok and we should be unit testing failure cases to ensure it never happens again.

**Comment by danieljhegeman** [comment]
closing in favor of #5163

**Pull request closed without merging**
