### PR TITLE
chore: update test id from `data-test-id` to `data-testid` to match default playwright configuration

### PR DESCRIPTION
**Pull request by charles-testco**
## Reason for Change

Currently we use the format data-test-id="menu" for test Ids.

We want to change this to:
data-testid="menu"

For several reasons:

- It is Playwright default format
- Will allow us to use Playwright command out of the box: getByTestId without writing our own wrapper
- Will fit with some Ids from external libraries

- #4458

## Changes

- modify
- data-test-id to data-testid

## Testing steps
Ensure all tests pass

### CODE REVIEW

**Comment by atarashansky** [comment]
Hi - this PR can be closed. I have an open PR refactoring our unit tests where I set the default test attribute to be `data-test-id` in the playwright config: https://github.com/chanzuckerberg/single-cell-data-portal/pull/4432/files#diff-1ed7245e0c7c634928b52839600c3d493c9d29150d369e9ab20979e61e7f8f97R56

If you need this to unblock your work, then please add the linked line to your config.

**Comment by tihuan** [comment]
I had set up `data-test-id` pattern way before Playwright went with `data-testid` as default (and still a little surprised that they went with that format, since that's not very HTML attribute looking format lol) 

But if switching to `data-testid` means one less customization in our system, I think it's worth doing it!

I was thinking the same thing Alec pointed out about us adding our own test id instead of relying on unofficial API third party libraries uses, but in this case it's unlikely existing libraries will change from `data-testid` to `data-test-id`, so I'm also fine relying on them if it means we get to write a little less code in our production code

**Comment by tihuan** [comment]
> > I had set up `data-test-id` pattern way before Playwright went with `data-testid` as default (and still a little surprised that they went with that format, since that's not very HTML attribute looking format lol)
> > But if switching to `data-testid` means one less customization in our system, I think it's worth doing it!
> > I was thinking the same thing Alec pointed out about us adding our own test id instead of relying on unofficial API third party libraries uses, but in this case it's unlikely existing libraries will change from `data-testid` to `data-test-id`, so I'm also fine relying on them if it means we get to write a little less code in our production code
> 
> Sounds good to me. I'll go ahead and make the necessary changes to my branch to dodge merge conflicts.

Thanks so much, Alec 🎉 !!

**Comment by ashin-czi** [comment]
frontend/src/views/WheresMyGene/components/HeatMap/components/YAxisChart/index.tsx

has a typo! 
https://github.com/chanzuckerberg/single-cell-data-portal/pull/4459/files#diff-e1359d72040323eb2beb360f986f33ac1914636781618ddf1aa744b92b02582cR98

**Comment by charles-testco** [comment]
> I was thinking the same thing Alec pointed out about us adding our own test id instead of relying on unofficial API third party libraries uses, but in this case it's unlikely existing libraries will change from `data-testid` to `data-test-id`, so I'm also fine relying on them if it means we get to write a little less code in our production code

It is butter vs magarine war. data-test-id was the convention and cypress recommends/sticks. But I notice that majority or react components/libraries use data-testid and that probably is why Playwright went that road. An example is the "We would appreciate your feedback, please fill out a" alert render

**Comment by atarashansky** [comment]
Closing this PR as these changes have been merged in #4432. Thanks for raising this, @charles-testco.

**Comment by tihuan** [comment]
> > I was thinking the same thing Alec pointed out about us adding our own test id instead of relying on unofficial API third party libraries uses, but in this case it's unlikely existing libraries will change from `data-testid` to `data-test-id`, so I'm also fine relying on them if it means we get to write a little less code in our production code
> 
> It is butter vs magarine war. data-test-id was the convention and cypress recommends/sticks. But I notice that majority or react components/libraries use data-testid and that probably is why Playwright went that road. An example is the "We would appreciate your feedback, please fill out a" alert render

Love the analogy 😂 Yeah so interesting how the community evolves, but a small change for us so that's all good!

Thanks again for bringing this up, Charles!

**Pull request closed without merging**
