### PR TITLE
docs: minor annotation editorial changes

### PR DESCRIPTION
**Pull request by ambrosejcarr**

### CODE REVIEW

**Comment by metakuni** [comment]
Checked with Ambrose/Max and merging this PR can wait til Jan

**Comment by atarashansky** [comment]
@MaximilianLombardo bumping for visibility

**Review by MaximilianLombardo — APPROVED** [review]
LGTM!

**Comment by MaximilianLombardo** [comment]
Thanks @atarashansky reviewed and approved!

**Pull request merged**
