### PR TITLE
feat: rds error should fail loudly in sfn

### PR DESCRIPTION
**Pull request by danieljhegeman**
## Reason for Change

- #6234 

## Changes

- exit(1) when cxg failure or seurat failure is present. Logging is already occurring locally as well as notification to slack.

## Testing steps

- Tests will come in follow-up but this should be incorporated asap for schema migration testing purposes.

## Checklist 🛎️

- [ ] Add product, design, and eng as reviewers for rdev review
- [ ] For UI changes, add screenshots/videos, so the reviewers know what you expect them to see
- [ ] For UI changes, add e2e tests to prevent regressions

### CODE REVIEW

**Review by nayib-jose-gloria — COMMENTED** [review]
This change works for cxg + seurat, but the original ticket mentions marking the sfn as failed upon errors in the validate step also. I'm not 100% sure if we should, since some validate failures will be intended failures (i.e. the curator submits an invalid dataset), but it would be helpful for debugging cases where the failure is unexpected. I'm not sure how simple it'd be to determine whether a validation error is expected or unexpected and handle accordingly. @Bento007 your thoughts?

We can decouple that change to unblock this, if we make a separate ticket for it

**Review by nayib-jose-gloria — COMMENTED** [review]
@Bento007, I believe, mentioned that it might be problematic to fail before we deregister the Job Definition. Am I recalling correctly? This step runs before then, so that'd be a problem if so

**Comment by danieljhegeman** [comment]
> @Bento007, I believe, mentioned that it might be problematic to fail before we deregister the Job Definition. Am I recalling correctly? This step runs before then, so that'd be a problem if so

@nayib-jose-gloria that's right, I'll fix that.

**Comment by Bento007** [comment]
When I was imaging the solution for this, i was assuming we could do it within in the SFN definition. When a step fails in the SFN it puts the error in the result passed to the next step. All we'd need to do is check for the existence of this error field in the resulting JSON and set the state to Failed. This check could then be done right after we deregister.

**Review by Bento007 — APPROVED** [review]
Will you also be catching error from download and validate in future work?

**Review by Bento007 — APPROVED** [review]
🔥

**Pull request merged**
