### PR TITLE
fix(fe-infra): add 'wasm-unsafe-eval' to CSP to allow for wasm

### PR DESCRIPTION
**Pull request by seve**
https://github.com/Touffy/client-zip#webassembly-and-content-security-policy

### CODE REVIEW

**Comment by tihuan** [comment]
Reading through https://github.com/WebAssembly/content-security-policy/blob/main/proposals/CSP.md, it sounds like adding `'wasm-unsafe-eval'` is the minimum we need to allow WASM execution. It sucks that it doesn't give us finer controls on what WASM modules we allow to execute (from which origins, etc.), but that would need to happen later when wasm has its own CSP directive!

**Review by tihuan — APPROVED** [review]

**Comment by tihuan** [comment]
CC @jakeyheath for visibility! Not sure if you see any immediate red flags by enabling `'wasm-unsafe-eval'` 🙏 Thank you!

**Comment by seve** [comment]
> . It sucks that it doesn't give us finer controls on what WASM modules we allow to execute (from which origins, etc.)

Maybe we should look into adding `strict-dynamic` and nonces?

**Comment by tihuan** [comment]
Yeah if @jakeyheath sees anything really bad with this directive, we could also use https://github.com/Stuk/jszip instead, which doesn't seem to use WASM!

**Comment by jakeyheath** [comment]
Whoaaaa WASM, how cool!

**Comment by jakeyheath** [comment]
I am actually unsure about this directive, I have never seen it before.

**Comment by tihuan** [comment]
Yeah today is my first day seeing it too 😆 

`strict-dynamic` is supported by our targeted browsers, but if we're caching SSR'd pages for SEO, then nonce won't work!

Something to discuss if we get there!

**Pull request merged**
