### PR TITLE
fix: rdev non-GHA builds

### PR DESCRIPTION
**Pull request by atolopko-czi**
### Reviewers
**Functional:** 

**Readability:** 

---

## Changes
Add explicit --stack-name option for GHA-based builds of docker images. Replaces the use of --extra-tag to pass in the stack name. This allows the script to work in non-GHA build usages.

## QA steps (optional)

Tested:
* single-cell-infra happy explorer + data portal rdev *local* create
* single-cell-infra happy explorer + data portal rdev *GHA* create
* single-cell-data-portal happy *local* create

### CODE REVIEW

**Comment by atolopko-czi** [comment]
> * single-cell-data-portal happy *local* create.

@tihuan This builds now, but app is not loading for me in rdev. This _is_ what you were trying to do when the bug was first reported, right? I wasn't sure if any engineers would try to build a portal-only rdev, but I can see that can still be useful. Would you mind testing in case it's just something on my end?

**Comment by tihuan** [comment]
Hurray! Thanks so much for fixing this, @atolopko-czi 🙏 At least for WMG prototype, I've been building portal only rdev, so this will be super useful!

Will test a build now!

**Comment by tihuan** [comment]
Woop woop! Can confirm the fix works for Portal Only rdev 🎉 🙏 

https://thuang-test-rdev-frontend.rdev.single-cell.czi.technology/

@atolopko-czi I think it didn't work for you probably because the FE servers were actually still building!

I waited to see `ready - started server on 0.0.0.0:9000, url: http://localhost:9000` via `./scripts/happy logs thuang-test-rdev frontend` and refreshed https://thuang-test-rdev-frontend.rdev.single-cell.czi.technology/ and the Bad Gateway error went away!

**Review by tihuan — APPROVED** [review]
LGTM!! Thanks so much again for fixing this 🙏 ! It's gonna make my WMG rdev deployment a lot easier 🎉 !

**Comment by atolopko-czi** [comment]
> `ready - started server on 0.0.0.0:9000, url: http://localhost:9000` via `./scripts/happy logs thuang-test-rdev frontend`

Ah, nice trick. I've added that to our rdev doc https://docs.google.com/document/d/1nynGcBS_TA55qlQo9WjINGkcMnE_xIBz7-inmop2bqo/

**Review by Bento007 — COMMENTED** [review]
How is `HAPPY_ENV` different from `happy_env`?

**Review by Bento007 — APPROVED** [review]

**Pull request merged**
